formatter: "markdown table"

sections:
  show:
    - providers
    - inputs
    - outputs
    - resources
    - modules
    - requirements

content: |-
  
  {{ .Providers }}
  
  {{ .Inputs }}
  
  {{ .Outputs }}
  
  {{ .Resources }}
  
  {{ .Modules }}

recursive:
  enabled: true

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->